### ISSUE TITLE
Magritte vs Mediapipe 

### ISSUE THREAD

**Issue by mamlekate** [google/magritte#11]
I have used Mediapipe for face detection using their tutorial code [here](https://google.github.io/mediapipe/solutions/face_detection.html).
I read that Magritte uses Mediapipe library under the hood, but I couldn't figure out if Magritte does a better job than Mediapipe in identifying faces. Have you compared their results?

**Comment by murilolima** [comment]
We use the [MediaPipe face detection models](https://google.github.io/mediapipe/solutions/models.html#face-detection) under the hood, but we provide a few extra graphs that combine different rotations, or the short-range and full-range models. Please refer to the [detection graphs documentation](https://google.github.io/magritte/technical_guide/graphs.html#detection) for more information.

We have not compared the results yet.
