### ISSUE TITLE
Magritte on Windows

### ISSUE THREAD

**Issue by mamlekate** [google/magritte#12]
I wanted to run Magritte on Windows using python. Could you show me the installation steps?

**Comment by murilolima** [comment]
We do not have specific instructions, but Magritte is based on [MediaPipe](https://mediapipe.dev/), which supports Windows and Python. Please refer to MediaPipe's [Windows installation instructions](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows) and [Python guide](https://google.github.io/mediapipe/getting_started/python.html). You could then use Magritte graphs to redact your content.
