### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by capsload2** [google/magritte#13]
Is there any known iOS App available with this API?

**Comment by stoman** [comment]
Magritte is based on [MediaPipe](https://mediapipe.dev/), which supports iOS. Refer to [MediaPipe's iOS installation instructions](https://google.github.io/mediapipe/getting_started/ios.html) and the [MediaPipe iOS examples on GitHub](https://github.com/google/mediapipe/tree/master/mediapipe/examples/ios) to get started. The iOS resources at [awesome-mediapipe](https://github.com/mgyong/awesome-mediapipe#ios) are also a good reference. You could then use Magritte graphs to redact your images and videos.
