### ISSUE TITLE
could u support ios ?

### ISSUE THREAD

**Issue by lxm1799** [google/magritte#9]
hello , i watch u project examples, don`t have ios demo , so i wish u can support ios 
1、support video
2、support static image
3、get result,such as score 
thanks

**Comment by murilolima** [comment]
We do not have plans to provide an iOS demo at the moment. However Magritte is based on [MediaPipe](https://mediapipe.dev/), which supports iOS. Please look at [MediaPipe's iOS installation instructions](https://google.github.io/mediapipe/getting_started/ios.html) and [MediaPipe iOS examples on GitHub](https://github.com/google/mediapipe/tree/master/mediapipe/examples/ios). You could then use Magritte graphs to redact your images and videos.

**Comment by stoman** [comment]
The iOS resources at [awesome-mediapipe](https://github.com/mgyong/awesome-mediapipe#ios) are also a good reference.

**Comment by lxm1799** [comment]
> 

currently . i konw how to build ios mediapipe demo,but i don`t konw how to get the confidance score,did u konw how to do ?
